import { Metadata } from 'next'
import Link from 'next/link'


export const metadata = {
  title: {
    default: "tutto",
    template: "%s | tutuorialr",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul
              style={{
                display: 'flex',
                flexDirection: 'row',
                justifyContent: 'space-between',
                paddingBottom: '1rem',
                borderBottom: '1px solid #ddd',
              }}>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/dashboard">Dashboard</Link>
              </li>
              <li>
                <Link href="/products">Products</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li>
                <Link href="/blog">Blog</Link>
              </li>
            </ul>
          </nav>
        </header>
        <div>
          {children}
        </div>
        <footer
          style={{
            display: 'flex',
            position: 'fixed',
            bottom: 0,
            width: '100%',
            justifyContent: 'center',
            border: '1px solid #ddd',
          }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
